### ISSUE TITLE
Error with async method

### ISSUE THREAD

**Issue by cernadasjuan** [spring-projects/spring-security-oauth2-boot#32]
Hi,

I need to perform a request using the Oauth2RestTemplate in an async method, but im getting an error with the Oauth2ClientContext (the session scope in not available in the new thread):

``
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:362) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:193) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at com.sun.proxy.$Proxy121.getAccessToken(Unknown Source) ~[na:na]
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:125) ~[spring-security-oauth2-2.2.2.RELEASE.jar:na]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:698) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:457) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at net.baymark.lokiadmin.repository.impl.RecipientRepositoryImpl.importToGroup(RecipientRepositoryImpl.java:47) ~[classes/:na]
	at net.baymark.lokiadmin.service.impl.RecipientServiceImpl.importToGroup(RecipientServiceImpl.java:105) ~[classes/:na]
	at net.baymark.lokiadmin.service.impl.RecipientServiceImpl.lambda$bulkUpload$0(RecipientServiceImpl.java:46) ~[classes/:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_121]
	at net.baymark.lokiadmin.service.impl.RecipientServiceImpl.bulkUpload(RecipientServiceImpl.java:46) ~[classes/:na]
	at net.baymark.lokiadmin.service.impl.RecipientServiceImpl$$FastClassBySpringCGLIB$$97d8b459.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) ~[spring-security-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.context.request.SessionScope.get(SessionScope.java:55) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 29 common frames omitted
``

There is a way to propagate the session scope in the new thread?

Thanks!

**Comment by FranDisalvo90** [comment]
Hi! I have the same problem. 

Thank you!

**Comment by emilianotebes** [comment]
Same trouble here. Not being able to propagate security scope to Oauth2RestTemplate.

**Comment by jzheaux** [comment]
@cernadasjuan Can you provide some additional detail on how you are launching the asynchronous task? For example, it is initially launched from HTTP traffic, or is it, say, on a timer?

Generally speaking, request and session-scoped beans are not available out of the box when on a separate thread. They need to be manually propagated when the thread is launched.

If you are using `@Async`, then customizing the async executor may work for you: https://stackoverflow.com/questions/23732089/how-to-enable-request-scope-in-async-task-executor/33337838#33337838

Or, I might not yet be understanding your issue--if you can provide a small sample that represents the behavior, then I'll play with it and see if I have any other recommendations.

**Comment by jzheaux** [comment]
@cernadasjuan I'm closing this, but feel free to reopen if you still need a hand.

**Comment by MayankManwansh** [comment]
@jzheaux  i am facing same issue while using CompletableFuture with @Async annotation for parallel processing. Is there any way to share the session and request scope beans between parent and child thread apart from way suggested in stackOverflow link provided above ?

**Comment by jzheaux** [comment]
@MayankManwansh I guess I don't understand how you are combining `CompletableFuture` with `@Async`, which is why this sounds like a really good question for StackOverflow, and I'd recommend that you ask it there.

Spring Security OAuth doesn't provide anything special to help out with this. 

See if this helps: https://stackoverflow.com/questions/47351435/spring-async-with-completablefuture

If not, please post your question to StackOverflow with the `spring` tag. (I would not recommend the `spring-security` tag as, at this point, it sounds like it isn't specific to that)
