### ISSUE TITLE
Fix settings.gradle on Windows

### ISSUE THREAD

**Issue by nintha** [spring-projects/spring-security-oauth2-boot#37]
Bug report

Version from gradle.properties
```
version=2.0.4.BUILD-SNAPSHOT
springSocialVersion=1.1.6.RELEASE
springBootVersion=2.0.3.RELEASE
```
OS: Windows 10
When I ran the project `spring-security-oauth2-boot\samples\spring-boot-sample-secure-oauth2` , something wrong in importing the project. Gradle said that
```
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.compile(Pattern.java:1704)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at java_lang_String$replaceAll$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at settings_brt72ubmesw8dl4l9ec8mibcw$_run_closure2.doCall(D:\spring-security-oauth2-boot\settings.gradle:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
// omitted
```

then I opened the file `spring-security-oauth2-boot\settings.gradle` and found the 19th line
```
String projectPath = buildFilePath.replace(rootDirPath, '').replaceAll(File.separator, ':')
```
and changed it to
```
String projectPath = buildFilePath.replace(rootDirPath, '').replace(File.separator, ':')
```
the problem had fixed. 
Please fix it in the source code. Thx.

In  the Windows, File.separator is "\\", but method `replaceAll` accept regex string, "\\" is escape character.
And method `replace` accept normal string, so it works.

**Comment by nintha** [comment]
Sure, I had submitted pr #38.

**Comment by rwinch** [comment]
Thanks @nintha! That is now merged into master
